/* MODEL SERVIÇO */

SELECT
CODPROD AS CodServico,
DESCRPROD AS Nome
FROM TGFPRO
WHERE CODGRUPOPROD = 20400

/*

SELECT DISTINCT  
	PRO.CODPROD AS CodServico,
	PRO.DESCRPROD AS Nome
 FROM AD_STOSRVCONT CONT
 INNER JOIN TGFPRO PRO ON CONT.CODPROD = PRO.CODPROD
WHERE CONT.NUMCONTRATO IN(1, 91)*/