    SELECT 
			EQP.CONTROLE AS CodSerie,
			SERIE.CONTROLEFAB AS CodSerieFab,			
			EQP.CODPARC AS CodParc,
			CON.CODPARC AS CodParcCon,
			PROD.DESCRPROD AS Nome,
			CON.NUMCONTRATO AS CodContrato
		FROM BH_FTLEQP EQP
			LEFT JOIN BH_FTLSER SERIE ON SERIE.CONTROLE = EQP.CONTROLE
			INNER JOIN TGFPRO PROD ON PROD.CODPROD = EQP.CODPROD
			INNER JOIN TCSCON CON ON CON.NUMCONTRATO = EQP.NUMCONTRATO



		--	 SELECT PROD.AD_MODELO,
		--	EQP.CODPARC,
		--	CON.CODPARC[CODPARCCON],
		--	PAR.NOMEPARC,
		--	EQP.CONTROLE,
		--	SERIE.CONTROLEFAB,			
		--	PROD.DESCRPROD,
		--	CON.NUMCONTRATO,
		--	NAT.DESCRNAT,
		--	ENDE.TIPO +' '+ ENDE.NOMEEND [NOMEEND],
		--    EQP.NUMEND,
		--	BAI.NOMEBAI,
		--	CID.NOMECID,
		--	ENDE.CODEND,
		--	CID.CODCID,
		--	BAI.CODBAI,		    			
		--    EQP.CEP,
		--    EQP.COMPLEMENTO,
		--	GRU.DESCRGRUPOPROD,
		--	PROD.CODGRUPOPROD,
		--	PROD.CODPROD,
		--	PROD.CODNAT
		--FROM BH_FTLEQP EQP
		--	LEFT JOIN BH_FTLSER SERIE ON SERIE.CONTROLE = EQP.CONTROLE
		--	INNER JOIN TGFPRO PROD ON PROD.CODPROD = EQP.CODPROD
		--	INNER JOIN TCSCON CON ON CON.NUMCONTRATO = EQP.NUMCONTRATO
		--	INNER JOIN TGFNAT NAT ON NAT.CODNAT = CON.CODNAT
		--	LEFT JOIN TSIBAI BAI ON EQP.CODBAI = BAI.CODBAI
		--	LEFT JOIN TSIEND ENDE ON EQP.CODEND = ENDE.CODEND
		--    LEFT JOIN TSICID CID ON EQP.CODCID = CID.CODCID
		--	INNER JOIN TGFGRU GRU ON GRU.CODGRUPOPROD = PROD.CODGRUPOPROD
		--	LEFT JOIN TGFPAR PAR ON EQP.CODPARC = PAR.CODPARC
			                                    