        SELECT 
			EQP.CODPARC AS CodParc,
			CON.CODPARC AS CodParcCon,
			CON.NUMCONTRATO AS Contrato,
			PAR.NOMEPARC AS Parceiro,
			EQP.CONTROLE AS Controle,
			SERIE.CONTROLEFAB AS ControleFab,			
			PROD.DESCRPROD AS DescrProd,			
			NAT.DESCRNAT AS DescrNat,
			ENDE.TIPO +' '+ ENDE.NOMEEND AS Endereco,
		    EQP.NUMEND AS Numero,
			BAI.NOMEBAI AS Bairro,
			CID.NOMECID AS Cidade,
			ENDE.CODEND AS CodEndereco,
			CID.CODCID AS CodCidade,
			BAI.CODBAI AS CodBairro,		    			
		    EQP.CEP AS Cep,
		    EQP.COMPLEMENTO AS Complemento,
			GRU.DESCRGRUPOPROD AS DescrGrupo,
			PROD.CODGRUPOPROD AS CodGrupo,
			PROD.CODPROD AS CodProduto,
			PROD.CODPROD AS CodProduto
		FROM BH_FTLEQP EQP
			LEFT JOIN BH_FTLSER SERIE ON SERIE.CONTROLE = EQP.CONTROLE
			INNER JOIN TGFPRO PROD ON PROD.CODPROD = EQP.CODPROD
			INNER JOIN TCSCON CON ON CON.NUMCONTRATO = EQP.NUMCONTRATO
			INNER JOIN TGFNAT NAT ON NAT.CODNAT = CON.CODNAT
			LEFT JOIN TSIBAI BAI ON EQP.CODBAI = BAI.CODBAI
			LEFT JOIN TSIEND ENDE ON EQP.CODEND = ENDE.CODEND
		    LEFT JOIN TSICID CID ON EQP.CODCID = CID.CODCID
			INNER JOIN TGFGRU GRU ON GRU.CODGRUPOPROD = PROD.CODGRUPOPROD
			LEFT JOIN TGFPAR PAR ON EQP.CODPARC = PAR.CODPARC

			WHERE 1 = 1
			AND EQP.CONTROLE = 'inter485'
			