/*  MODEL SÉRIE  */
	
	SELECT 
			EQP.CONTROLE AS CodSerie,
			PROD.DESCRPROD AS Nome
		FROM BH_FTLEQP EQP
			LEFT JOIN BH_FTLSER SERIE ON SERIE.CONTROLE = EQP.CONTROLE
			INNER JOIN TGFPRO PROD ON PROD.CODPROD = EQP.CODPROD
			INNER JOIN TCSCON CON ON CON.NUMCONTRATO = EQP.NUMCONTRATO
			WHERE EQP.CONTROLE IS NOT NULL
			AND EQP.CODPARC = 1
			AND EQP.NUMCONTRATO = 96

