        SELECT 
			EQP.CODPARC AS CodParc,
			CON.CODPARC AS CodParcCon,
			CON.NUMCONTRATO AS Contrato,
			PAR.NOMEPARC AS Parceiro,
			EQP.CONTROLE AS Controle,
			SERIE.CONTROLEFAB AS ControleFab,			
			PROD.DESCRPROD AS DescrProd,			
			NAT.DESCRNAT AS DescrNat,
			CONCAT_WS(' ', ENDE.TIPO, ENDE.NOMEEND) AS Endereco,
		    EQP.NUMEND AS Numero,
			BAI.NOMEBAI AS Bairro,
			CID.NOMECID AS Cidade,
			ENDE.CODEND AS CodEndereco,
			CID.CODCID AS CodCidade,
			BAI.CODBAI AS CodBairro,		    			
		    EQP.CEP AS Cep,
		    EQP.COMPLEMENTO AS Complemento,
			GRU.DESCRGRUPOPROD AS DescrGrupo,
			PROD.CODGRUPOPROD AS CodGrupo,
			PROD.CODPROD AS CodProduto
		FROM BH_FTLEQP EQP
			LEFT JOIN BH_FTLSER SERIE WITH(NOLOCK) ON SERIE.CONTROLE = EQP.CONTROLE
			INNER JOIN TGFPRO PROD WITH(NOLOCK) ON PROD.CODPROD = EQP.CODPROD
			INNER JOIN TCSCON CON WITH(NOLOCK) ON CON.NUMCONTRATO = EQP.NUMCONTRATO
			INNER JOIN TGFNAT NAT WITH(NOLOCK) ON NAT.CODNAT = CON.CODNAT
			LEFT JOIN TSIBAI BAI WITH(NOLOCK) ON EQP.CODBAI = BAI.CODBAI
			INNER JOIN TSIEND ENDE WITH(NOLOCK) ON EQP.CODEND = ENDE.CODEND
		    LEFT JOIN TSICID CID WITH(NOLOCK) ON EQP.CODCID = CID.CODCID
			INNER JOIN TGFGRU GRU WITH(NOLOCK) ON GRU.CODGRUPOPROD = PROD.CODGRUPOPROD
			LEFT JOIN TGFPAR PAR WITH(NOLOCK) ON EQP.CODPARC = PAR.CODPARC

			WHERE 1 = 1
			AND EQP.CONTROLE = 'UKX000553'
			OR SERIE.CONTROLEFAB = 'UKX000553'
			

			--select * from TSIEND WHERE CODEND = 412017