
--SELECT * FROM AD_STOTAR WHERE EXECUTIONID = 37982

--SELECT * FROM AD_STOVST ORDER BY EXECUTIONID DESC
--SELECT * FROM AD_STOVST WHERE EXECUTIONID = 47112


 DECLARE @executionId INT

 SET @executionId = 47467

			SELECT EXECUTIONID AS ExecutionId
				  ,DHINI AS DataInicio
				  ,DHFIN AS DataFinal
				  ,SOLUCAOAPL AS Solucao
				  ,ACTIVITIID AS ActivitId
			FROM AD_STOTAR 
			WHERE DHINI IS NOT NULL 
			AND DHFIN IS NOT NULL 
			AND EXECUTIONID = @executionId 
			AND SOLUCAOAPL IS NOT NULL
			AND ACTIVITIID = (SELECT MAX(ACTIVITIID) FROM AD_STOTAR WHERE EXECUTIONID = @executionId)
			UNION ALL
			SELECT EXECUTIONID
				  ,DHINI
				  ,DHFIN
				  ,SOLUCAOAPL
				  ,ACTIVITIID
			FROM AD_STOVST 
			WHERE DHINI IS NOT NULL 
			AND DHFIN IS NOT NULL
			AND SOLUCAOAPL IS NOT NULL 
			AND EXECUTIONID = @executionId 
			AND ACTIVITIID = (SELECT MAX(ACTIVITIID) FROM AD_STOVST WHERE EXECUTIONID = @executionId)

