SELECT	
        EQP.CONTROLE AS Serie,
		PRO.DESCRPROD AS Produto,
		EQP.SITUACAO,
		CON.NUMCONTRATO AS Contrato,
		CON.CODPARC AS CodParcCon,
		PAR.NOMEPARC AS NomeParcCon,
        EQP.CODPARC AS CodParcAtendido,
		PAREQP.RAZAOSOCIAL AS NomeParcAtendido
	FROM BH_FTLEQP EQP WITH (NOLOCK)
	INNER JOIN TCSCON CON  WITH (NOLOCK) ON EQP.NUMCONTRATO = CON.NUMCONTRATO
	LEFT JOIN BH_FTLSER SERIE ON SERIE.CONTROLE = EQP.CONTROLE
	INNER JOIN TGFPAR PAR WITH (NOLOCK) ON PAR.CODPARC = CON.CODPARC
    INNER JOIN TGFPAR PAREQP WITH (NOLOCK) ON PAREQP.CODPARC=EQP.CODPARC
	INNER JOIN TGFPRO PRO WITH(NOLOCK) ON PRO.CODPROD = EQP.CODPROD 
   WHERE EQP.CONTROLE LIKE  '13334%'
   OR SERIE.CONTROLEFAB LIKE 'UKX000553%'

