/*  MODEL SÉRIE  */
	
SELECT TOP 100
	SERIE.CONTROLE AS Controle,
	SERIE.CONTROLEFAB AS ControleFab,
	PROD.DESCRPROD AS DescrProd
FROM BH_FTLEQP EQP
	LEFT JOIN BH_FTLSER SERIE ON SERIE.CONTROLE = EQP.CONTROLE
	INNER JOIN TGFPRO PROD ON PROD.CODPROD = EQP.CODPROD
	INNER JOIN TCSCON CON ON CON.NUMCONTRATO = EQP.NUMCONTRATO
	INNER JOIN TGFGRU GRU WITH(NOLOCK) ON GRU.CODGRUPOPROD = PROD.CODGRUPOPROD
	WHERE EQP.CONTROLE IS NOT NULL 
	AND	EQP.SITUACAO = 'A' 
	AND SERIE.CONTROLEFAB LIKE '1%'

			--WHERE EQP.CONTROLE IS NOT NULL
			--AND EQP.CODPARC = 1
			--AND EQP.NUMCONTRATO = 96