SELECT 
	EXECUTIONID AS ExecutionId, 
    NUMVISITA AS NumeroVisita, 
    DHINI AS DataInicio,
    DHFIN AS DataFinal,    
    DEFEITOCONS AS Defeito, 
    CAUSADEF AS Causa, 
    SOLUCAOAPL AS Solucao 
FROM AD_STOVST WHERE 1 = 1
ORDER BY NUVISITA DESC
--AND EXECUTIONID = {0} ORDER BY NUMVISITA DESC