/* MODEL USUARIO PORTAL */



SELECT 
	PRL.IDUSUPRTL AS CodUsuario, 
	PRL.NOMEUSU AS Nome
FROM AD_USUPRTL PRL
INNER JOIN AD_USUPRTLCON PARCON WITH(NOLOCK) ON PARCON.IDUSUPRTL = PRL.IDUSUPRTL
WHERE PRL.NOMEUSU IS NOT NULL
AND PARCON.NUMCONTRATO IN (368)
--AND NU IN (11614)


