declare @pLogin varchar(40), @password varchar(40)

SET @pLogin = 'fagner.gomes'
SET @password = 'alfa@4721'

SELECT PRTL.IDUSUPRTL AS IdUsuario,
	CTT.NOMECONTATO AS Nome,
	PRTL.PSWUSU AS Password,
	PRTL.LGNUSU AS Login,
	PRTL.PRFLUSU AS Perfil,
	CTT.EMAIL AS Email,
    CTT.TELEFONE AS Telefone,
	PRTL.ALTPSW AS AltPassword,
	PRTL.RGSTOCOR AS RgtOcorrencia,
	PRTL.CODPARC AS CodParc,
	PRTL.CODCONTATO AS CodContato,
	STUFF((SELECT ', ' + RTRIM(CON.CODPARCAT) AS [text()]
	FROM AD_USUPRTLCON CON
	WHERE CON.IDUSUPRTL = PRTL.IDUSUPRTL
	FOR XML PATH('')), 1, 1, '' ) AS CodParcAt,
	STUFF((SELECT ', ' + RTRIM(CON.CODPARCAB) AS [text()]
	FROM AD_USUPRTLCON CON
	WHERE CON.IDUSUPRTL = PRTL.IDUSUPRTL
	FOR XML PATH('')), 1, 1, '' ) AS CodParcAb,
	STUFF((SELECT ', ' + RTRIM(CON.NUMCONTRATO) AS [text()]
	FROM AD_USUPRTLCON CON
	WHERE CON.IDUSUPRTL = PRTL.IDUSUPRTL
	FOR XML PATH('')), 1, 1, '' ) AS NumContrato
	FROM AD_USUPRTL PRTL
	INNER JOIN TGFCTT CTT WITH(NOLOCK) ON CTT.CODCONTATO = PRTL.CODCONTATO AND CTT.CODPARC = PRTL.CODPARC
    WHERE PRTL.LGNUSU = @pLogin AND PRTL.PSWUSU = @password