

/* MODEL LOGIN

declare @UserName varchar(40), @Password varchar(40)
SET @UserName = 'fagner.gomes'
SET @Password = 'alfa@4721'

SELECT 
	PRTL.IDUSUPRTL AS IdUsuario,
	CTT.NOMECONTATO AS Nome,
	PRTL.LGNUSU AS UserName
	FROM AD_USUPRTL PRTL
	INNER JOIN TGFCTT CTT WITH(NOLOCK) ON CTT.CODCONTATO = PRTL.CODCONTATO AND CTT.CODPARC = PRTL.CODPARC
    WHERE PRTL.LGNUSU = @UserName AND PRTL.PSWUSU = @Password

*/

/* MODEL USUARIO

SELECT 
	PRTL.IDUSUPRTL AS IdUsuario,
	CTT.NOMECONTATO AS Nome,
	PRTL.LGNUSU AS Login,
	CTT.EMAIL AS Email,
    CTT.TELEFONE AS Telefone
	FROM AD_USUPRTL PRTL
	INNER JOIN TGFCTT CTT WITH(NOLOCK) ON CTT.CODCONTATO = PRTL.CODCONTATO AND CTT.CODPARC = PRTL.CODPARC
    WHERE PRTL.IDUSUPRTL = 337

*/

/* QUERY PARA USUÁRIO DETAILS */

SELECT 
	PRTL.IDUSUPRTL as IdUsuario,
	PRTL.ALTPSW AS AltPassword,
	PRTL.PRFLUSU AS Perfil,
	PRTL.RGSTOCOR AS RgtOcorrencia,
	STUFF((SELECT ', ' + RTRIM(CON.CODPARCAT) AS [text()]
	FROM AD_USUPRTLCON CON
	WHERE CON.IDUSUPRTL = PRTL.IDUSUPRTL
	FOR XML PATH('')), 1, 1, '' ) AS ClienteAt,
	STUFF((SELECT ', ' + RTRIM(CON.CODPARCAB) AS [text()]
	FROM AD_USUPRTLCON CON
	WHERE CON.IDUSUPRTL = PRTL.IDUSUPRTL
	FOR XML PATH('')), 1, 1, '' ) AS ClienteAb,
	STUFF((SELECT ', ' + RTRIM(CON.NUMCONTRATO) AS [text()]
	FROM AD_USUPRTLCON CON
	WHERE CON.IDUSUPRTL = PRTL.IDUSUPRTL
	FOR XML PATH('')), 1, 1, '' ) AS NumContrato
	FROM AD_USUPRTL PRTL
    WHERE PRTL.IDUSUPRTL = 337
	
