SELECT 
	VIN.EXECUTIONID AS ExecutionId, 
	DHINIC AS DataInicio,
	DHTERM AS DataFinal
	FROM AD_STOVIN VIN 
	INNER JOIN BH_BPMATV ATV ON ATV.EXECUTIONID = VIN.EXECUTIONID 
	AND ATV.ACTIVITIID = VIN.ACTIVITIID  
	WHERE 1 = 1
	--AND VIN.EXECUTIONID = {0}
	AND ATV.DHTERM IS NOT NULL
    ORDER BY VIN.EXECUTIONID DESC