SELECT 
     DISTINCT 
     PRO.CODGRUPOPROD AS CodGrupo
    ,GRU.DESCRGRUPOPROD	AS DescGrupo									
FROM TGFPRO PRO 
INNER JOIN TGFGRU GRU  WITH(NOLOCK) ON GRU.CODGRUPOPROD = PRO.CODGRUPOPROD
LEFT JOIN BH_FTLEQP EQP WITH(NOLOCK) ON EQP.CODPROD = PRO.CODPROD

WHERE 1 = 1
AND EQP.SITUACAO = 'A'
--AND EQP.NUMCONTRATO = 396
AND EQP.CODPARC = 1
ORDER BY DescGrupo