SELECT EQP.CONTROLE,
       PRO2.DESCRPROD,
       PRO2.AD_MODELO,
       PRO.DESCRPROD,
       EQP.NUMCONTRATO,
       PRO.CODPROD,
       GRU.DESCRGRUPOPROD AS GRUPOOCORRENCIA
FROM BH_FTLEQP EQP
INNER JOIN AD_STOSRVCONT CONT ON CONT.NUMCONTRATO = EQP.NUMCONTRATO
AND CONT.SEQUENCIA = EQP.SEQUENCIA
INNER JOIN TGFPRO PRO ON PRO.CODPROD = CONT.CODPROD
INNER JOIN TGFPRO PRO2 ON PRO2.CODPROD = EQP.CODPROD
INNER JOIN TGFGRU GRU ON GRU.CODGRUPOPROD =PRO.CODGRUPOPROD
WHERE  1 = 1
  AND EQP.CODPROD = 27026
--AND EQP.CONTROLE = 'XY0001265'
  AND EQP.NUMCONTRATO = 1089