DECLARE @pPagina INT, @pTamPag INT
SET @pPagina = 1
SET @pTamPag = 300

/* MODEL CONTATO */
SELECT TOP 100
	CTT.NOMECONTATO AS Nome,
	CTT.CODCONTATO AS CodContato
FROM TGFCTT CTT
WHERE 1 = 1 
AND CTT.NOMECONTATO LIKE 'FA%'
--AND CTT.CODPARC IN (1)
--AND CTT.NOMECONTATO LIKE 'fag%'

		