SELECT   CTT.CODCONTATO AS CodContato
		,CTT.NOMECONTATO AS Nome
		,CTT.TELEFONE AS Telefone
		,CTT.EMAIL AS Email
		,EQP.CONTROLE
	FROM BH_FTLEQP EQP
		INNER JOIN TGFCTT CTT WITH(NOLOCK) ON CTT.CODPARC = EQP.CODPARC    
	WHERE  1 = 1
	AND EQP.SITUACAO = 'A' 
	AND EQP.CONTROLE = '123 - teste tania'
