SELECT COUNT(*) FROM AD_STOOCO OCO 
    INNER JOIN TGFPAR PAR WITH(NOLOCK) ON PAR.CODPARC = OCO.CODPARC
    LEFT JOIN TSIEND ENDE WITH(NOLOCK) ON ENDE.CODEND = OCO.CODEND
    LEFT JOIN TSICID CID WITH(NOLOCK) ON CID.CODCID = OCO.CODCID 
	LEFT JOIN [TSIBAI] BAI WITH(NOLOCK) ON BAI.CODBAI = OCO.CODBAI 
    LEFT JOIN TSIUFS TSI WITH(NOLOCK) ON TSI.CODUF = CID.UF
	INNER JOIN BH_BPMEXC EXC WITH(NOLOCK) ON EXC.EXECUTIONID = OCO.EXECUTIONID
	LEFT JOIN TGFPRO PROD WITH(NOLOCK) ON PROD.CODPROD = OCO.CODPROD
	INNER JOIN TDDOPC OPC WITH(NOLOCK) ON OCO.SITUACAO = OPC.VALOR AND OPC.NUCAMPO = 9999990522
	WHERE 1 = 1  AND EXC.DHSLATS <= CONVERT(VARCHAR,'05/30/2017 23:59:59',103) 