DECLARE @pPagina INT, @pTamPag INT, @pCodParceiro nvarchar(100), @filtroWhere varchar(30), @pNumSerie varchar(40)

SET @pPagina = 1
SET @pTamPag = 5000
SET @pCodParceiro = '91'
SET @filtroWhere = LOWER('%%')
SET @pNumSerie = '39021292369'

	SELECT
		CON.NUMCONTRATO AS CodContrato,
		PAR.NOMEPARC AS Nome
		FROM TCSCON CON
		INNER JOIN TGFPAR PAR  WITH(NOLOCK) ON PAR.CODPARC = CON.CODPARC
		WHERE 1 = 1
		AND CON.NUMCONTRATO <> 0
		AND CON.ATIVO = 'S'


			--SELECT CON.NUMCONTRATO
			--		,PAR.CODPARC
			--		,PAR.RAZAOSOCIAL
			--		,NAT.DESCRNAT
			--		,CON.AD_CONTRATOCRM
			--		,CON.ATIVO
			--		,CON.CODPARC[CODPARCCON]
			--		,ENDE.TIPO +' '+ ENDE.NOMEEND [NOMEEND]
			--		,ENDE.CODEND
			--		,PAR.NUMEND
			--		,BAI.CODBAI
			--		,BAI.NOMEBAI
			--		,CID.CODCID
			--		,CID.NOMECID
			--		,PAR.CEP
			--		,PAR.COMPLEMENTO
			--		FROM TGFPAR PAR
			--		INNER JOIN TCSCON CON ON PAR.CODPARC = CON.CODPARC
			--		LEFT JOIN TGFNAT NAT ON NAT.CODNAT = CON.CODNAT
			--		LEFT JOIN TSIBAI BAI ON PAR.CODBAI = BAI.CODBAI
			--		LEFT JOIN TSIEND ENDE ON PAR.CODEND = ENDE.CODEND
			--		LEFT JOIN TSICID CID ON PAR.CODCID = CID.CODCID
			--		 WHERE 1 = 1 
			--		 AND CON.NUMCONTRATO <> 0
			--		 --AND (CON.NUMCONTRATO IN(187, 401, 96))
			--		 --AND PAR.CODPARC = 1 
			--		 AND CON.ATIVO = 'S'


