SELECT 
	 CON.NUMCONTRATO AS Contrato
	,PAR.CODPARC AS CodParc
	,PAR.RAZAOSOCIAL AS RazaoSocial
	,NAT.DESCRNAT AS DescrNat
	,CON.CODPARC AS CodParcCon
	,ENDE.TIPO +' '+ ENDE.NOMEEND AS Endereco
	,ENDE.CODEND AS CodEndereco
	,PAR.NUMEND AS Numero
	,BAI.CODBAI	AS CodBairro
	,BAI.NOMEBAI AS Bairro
	,CID.CODCID AS CodCidade
	,CID.NOMECID AS Cidade
	,PAR.CEP
	,PAR.COMPLEMENTO
FROM TGFPAR PAR
INNER JOIN TCSCON CON ON PAR.CODPARC = CON.CODPARC
LEFT JOIN TGFNAT NAT ON NAT.CODNAT = CON.CODNAT
LEFT JOIN TSIBAI BAI ON PAR.CODBAI = BAI.CODBAI
LEFT JOIN TSIEND ENDE ON PAR.CODEND = ENDE.CODEND
LEFT JOIN TSICID CID ON PAR.CODCID = CID.CODCID
WHERE CON.NUMCONTRATO = 96
